version: '3.8'

services:
  db:
    container_name: pg16
    build: ./docker/db/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dvdrental
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dvdrental
      TZ: 'Asia/Tokyo'
    restart: always

  pgadmin:
    container_name: pgadmin48
    build:
      context: ./docker/pgadmin
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
    depends_on:
      - db

volumes:
  volume_pgadmin:
    name: vpga
